/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'lesson_delivery_app_ui';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String DELIVERY = 'assets/delivery.json';
  static const String EXAMPRACTICE = 'assets/images/exampractice.jpg';
  static const String EXAMREAL = 'assets/images/examreal.jpg';
  static const String MEDIAMP3 = 'assets/images/mediamp3.jpg';
  static const String MEDIAMP4 = 'assets/images/mediamp4.jpg';
  static const String MEDIAPDF = 'assets/images/mediapdf.jpg';
  static const String MEDIAYOUTUBE = 'assets/images/mediayoutube.jpg';
  static const String QUESTION = 'assets/images/question.jpg';
}
